GET http://localhost:8080/api/ip?ip=1.1.1.1

###
GET http://localhost:8080/api/ip

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "kzw200015",
  "password": "15261841015kzw"
}