GET http://localhost:8080/api/ip?ip=1.1.1.1

###
GET http://localhost:8080/api/ip

### 注册
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": {{username}},
  "password": {{password}}
}

### 登录
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": {{username}},
  "password": {{password}}
}

### 我
GET http://localhost:8080/api/users/me
Token: 42868646-254e-4e4a-945f-05aa4fd4bb0f

### 获取单个文章
GET http://localhost:8080/api/posts/1

### 获取多个文章
GET http://localhost:8080/api/posts?page=1&size=10